### ISSUE TITLE
Design suggestions from the community

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/ark-explorer#13]
https://www.reddit.com/r/ArkEcosystem/comments/74fxq7/explorer_my_view_redesign/

https://i.imgur.com/KP0lZ2j.png

https://i.imgur.com/9efRNH3.png

Just wanted to let you know. Maybe it helps to shape ideas for future development.

It was submitted by https://www.reddit.com/user/its_dhe_

**Comment by nikolamircic** [comment]
I agree with Belgium designer guy. I suppose because I am a UX designer too. 
So here are my suggestions:

* make font more legible, bigger. You can use just one font, no need for two different fonts for headings and body.
* flat design is better for data heavy content, please remove shadows around boxes
* chart animation is too slow, it's better just to appear instantly than be animated (people visiting are here for a quick lookup, not fancy animations)
* search field is not obvious enough. it looks like a label. put a frame around it
* "See All Blocks" button, ... well.... just remove the shading it's not very premium looking

I think ARK is one of the best blockchain projects and it deserves best UI. So this comments are really because I love ARK not hate it.

**Comment by rby123** [comment]
I agree. Personally, I also think putting a box around each row is too much visually. WE also lost the ability to sort the columns in the delegate monitor section, a feature I previously found very useful. Also the search function does not work well. For example, if you search 'rob' the return is astrobob.
